### ISSUE TITLE
Too big username

### ISSUE THREAD

**Issue by belauzas** [student-to-dev/twitter-clone-php#35]
Let's limit to 32 symbols.

![image](https://user-images.githubusercontent.com/7464725/210266827-6c992844-e82e-4b77-a689-e0584be443ad.png)

Question - how to deal with an existing users? 🤔

**Comment by SergejsRom** [comment]
For the wiew can show part of username


![Image](https://user-images.githubusercontent.com/101097144/210679041-da67c509-c5e8-412b-942b-4fb87a065d34.png)
